@startuml
!define RECTANGLE component
title Уровень контейнеров

actor Пользователь
actor Администратор

RECTANGLE Клиент {
  (Веб-приложение)
}

RECTANGLE Сервер {
  (Серверное приложение)
}

RECTANGLE Данные {
  (База данных)
}

Пользователь -- (Веб-приложение)
Администратор -- (Веб-приложение)
(Веб-приложение) --> (Серверное приложение)
(Серверное приложение) --> (База данных)

@enduml
