@startuml
!define RECTANGLE class
title Контекстный уровень

actor Пользователь
RECTANGLE ВебПриложение {
  Пользователь -- (Веб-сайт)
}

actor Администратор
RECTANGLE ПанельАдминистратора {
  Администратор -- (Панель администратора)
}

RECTANGLE Сервер {
  (Веб-сайт) --> (Сервер)
  (Панель администратора) --> (Сервер)
}

RECTANGLE БазаДанных {
  (Сервер) --> (База данных)
}

@enduml
