@startuml
title Диаграмма бизнес-архитектуры

actor Клиент
actor Администратор

rectangle Система {
  usecase "Запрос информации о продукте" as UC1
  usecase "Покупка продукта" as UC2
  usecase "Отслеживание заказа" as UC3
  usecase "Управление продуктами" as UC4
  usecase "Управление клиентами" as UC5
}

Клиент --> UC1
Клиент --> UC2
Клиент --> UC3
Администратор --> UC4
Администратор --> UC5

@enduml
