@startuml
title Диаграмма QA тестов

actor Тестировщик

rectangle "Тесты для функциональности регистрации" {
  usecase "Тест на успешную регистрацию" as UC1
  usecase "Тест на ошибку регистрации" as UC2
}

rectangle "Тесты для функциональности оформления заказа" {
  usecase "Тест на успешное оформление заказа" as UC3
  usecase "Тест на ошибку оформления заказа" as UC4
}

rectangle "Тесты для функциональности управления каталогом" {
  usecase "Тест на успешное добавление товара" as UC5
  usecase "Тест на ошибку добавления товара" as UC6
}

rectangle "Тесты для возврата товара" {
  usecase "Тест на успешный возврат товара" as UC7
  usecase "Тест на ошибку возврата товара" as UC8
}

rectangle "Тесты для взаимодействия с внешними системами" {
  usecase "Тесты на успешную обработку платежей" as UC9
  usecase "Тесты на интеграцию со складской системой" as UC10
  usecase "Тесты на интеграцию с системой логистики" as UC11
}

Тестировщик --> UC1
Тестировщик --> UC2
Тестировщик --> UC3
Тестировщик --> UC4
Тестировщик --> UC5
Тестировщик --> UC6
Тестировщик --> UC7
Тестировщик --> UC8
Тестировщик --> UC9
Тестировщик --> UC10
Тестировщик --> UC11

@enduml

