@startuml
title Activity Diagram: Управление пользователями

|Пользователь|
start
:Регистрируется;
:Авторизуется;
:Редактирует профиль;

|Администратор|
:Блокирует пользователя;
:Разблокирует пользователя;

|Система|
:Автоматически обновляет данные о пользователях в базе данных;
:Уведомляет администратора о изменениях статуса пользователей;

stop
@enduml
