@startuml
title Activity Diagram: Управление каталогом

|Администратор|
start
:Авторизуется в панели управления;
:Добавляет новый товар;
:Редактирует товар;
:Удаляет товар;

|Система|
:Автоматически обновляет данные о товарах в базе данных;
:Уведомляет пользователей о новых товарах и изменениях;

stop
@enduml
