@startuml
start
:Пользователь заходит на сайт;
:Пользователь ищет товар;
:Пользователь просматривает товар;
:Пользователь добавляет товар в корзину;
:Пользователь оформляет заказ;
:Пользователь выбирает способ оплаты и доставки;
:Пользователь подтверждает заказ;
:Система отправляет уведомление о подтверждении заказа;

stop
@enduml
