@startuml
title Activity Diagram: Обработка отмены заказа

|Пользователь|
start
:Заходит в личный кабинет;
:Выбирает заказ для отмены;
:Отправляет запрос на отмену;

|Система|
:Автоматически проверяет статус заказа;
if (Статус позволяет отмену) then (да)
  :Автоматически подтверждает отмену;
else (нет)
  :Отклоняет отмену;
endif
:Отправляет уведомление о статусе отмены;

|Пользователь|
:Получает уведомление о статусе отмены;

stop
@enduml
