@startuml
title Диаграмма активности: Процесс покупки

|Покупатель|
start
:Зайти на сайт;
:Искать товар;
:Просмотреть детали товара;
:Добавить товар в корзину;
:Перейти к оформлению заказа;
:Выбрать способ оплаты и доставки;
:Подтвердить заказ;
|Система|
:Отправить уведомление о подтверждении заказа;
stop
@enduml
