@startuml
actor Покупатель
actor Администратор

usecase "Регистрация" as UC1
usecase "Авторизация" as UC2
usecase "Поиск товаров" as UC3
usecase "Просмотр товаров" as UC4
usecase "Добавление в корзину" as UC5
usecase "Оформление заказа" as UC6
usecase "Просмотр профиля" as UC7
usecase "История заказов" as UC8
usecase "Оставление отзывов" as UC9
usecase "Получение уведомлений" as UC10
usecase "Возврат товара" as UC11
usecase "Отмена заказа" as UC12
usecase "Обращение в службу поддержки" as UC13

usecase "Добавление товаров" as UC14
usecase "Редактирование товаров" as UC15
usecase "Удаление товаров" as UC16
usecase "Управление пользователями" as UC17
usecase "Просмотр и управление заказами" as UC18
usecase "Управление отзывами" as UC19
usecase "Обработка запросов на возврат" as UC20
usecase "Обработка запросов на отмену заказа" as UC21
usecase "Обработка жалоб и запросов через службу поддержки" as UC22

usecase "Система изменяет статус заказа" as UC23
usecase "Система управляет пользователями" as UC24
usecase "Система обрабатывает возвраты" as UC25
usecase "Система обрабатывает отмены заказа" as UC26

Покупатель --> UC1
Покупатель --> UC2
Покупатель --> UC3
Покупатель --> UC4
Покупатель --> UC5
Покупатель --> UC6
Покупатель --> UC7
Покупатель --> UC8
Покупатель --> UC9
Покупатель --> UC10
Покупатель --> UC11
Покупатель --> UC12
Покупатель --> UC13

Администратор --> UC2
Администратор --> UC14
Администратор --> UC15
Администратор --> UC16
Администратор --> UC17
Администратор --> UC18
Администратор --> UC19
Администратор --> UC20
Администратор --> UC21
Администратор --> UC22

UC18 --> UC23 : include
UC17 --> UC24 : include
UC20 --> UC25 : include
UC21 --> UC26 : include

@enduml

