@startuml
actor Пользователь

rectangle ВебПриложение {
    Пользователь --> (Запрос на просмотр страниц)
    Пользователь --> (Поиск товаров)
    Пользователь --> (Добавление в корзину)
    Пользователь --> (Оформление заказа)
}

rectangle Сервер {
    (Запрос на просмотр страниц) --> (Обработка запросов)
    (Поиск товаров) --> (Обработка запросов)
    (Добавление в корзину) --> (Обработка запросов)
    (Оформление заказа) --> (Обработка запросов)
}

rectangle БазаДанных {
    (Обработка запросов) --> (Запрос на получение и сохранение данных)
    (Запрос на получение и сохранение данных) --> (Ответ на запросы)
}

Сервер --> ВебПриложение: Ответ на запросы
ВебПриложение --> Пользователь: Отображение информации, уведомления

@enduml
