@startuml
title Диаграмма потока данных

actor Пользователь

rectangle ВебПриложение {
  Пользователь --> (Запрос на просмотр продуктов)
  (Запрос на просмотр продуктов) --> СерверноеПриложение : Запрос данных
  СерверноеПриложение --> БазаДанных : Запрос данных о продуктах
  БазаДанных --> СерверноеПриложение : Ответ с данными
  СерверноеПриложение --> ВебПриложение : Ответ с данными
  ВебПриложение --> Пользователь : Отображение данных
}

@enduml
