@startuml
title Логическая модель базы данных

entity Пользователи {
  * ID: int
  * Имя: string
  * Email: string
  * Пароль: string
  * Роль: string
}

entity Товары {
  * ID: int
  * Название: string
  * Описание: string
  * Категория: string
  * Цена: float
  * Наличие: int
}

entity Заказы {
  * ID: int
  * ПользовательID: int
  * Дата: date
  * Статус: string
  * СпособОплаты: string
  * СпособДоставки: string
}

entity Отзывы {
  * ID: int
  * ТоварID: int
  * ПользовательID: int
  * Рейтинг: int
  * Комментарий: string
  * Дата: date
}

entity Уведомления {
  * ID: int
  * ПользовательID: int
  * Сообщение: string
  * Дата: date
  * Статус: string
}

Пользователи ||--o{ Заказы
Пользователи ||--o{ Отзывы
Пользователи ||--o{ Уведомления
Товары ||--o{ Отзывы
Заказы ||--|{ Товары

@enduml
