@startuml
entity "Пользователь" {
    + ID: INT [PK]
    * Имя: VARCHAR
    * Email: VARCHAR
    * Пароль: VARCHAR
    * Роль: VARCHAR
}

entity "Товар" {
    + ID: INT [PK]
    * Название: VARCHAR
    * Описание: TEXT
    * Категория: VARCHAR
    * Цена: DECIMAL
    * Наличие на складе: INT
}

entity "Заказ" {
    + ID: INT [PK]
    * ПользовательID: INT [FK]
    * Дата заказа: DATE
    * Статус: VARCHAR
    * Способ оплаты: VARCHAR
    * Способ доставки: VARCHAR
}

entity "Отзыв" {
    + ID: INT [PK]
    * ТоварID: INT [FK]
    * ПользовательID: INT [FK]
    * Рейтинг: INT
    * Комментарий: TEXT
    * Дата: DATE
}

entity "Уведомление" {
    + ID: INT [PK]
    * ПользовательID: INT [FK]
    * Сообщение: TEXT
    * Дата: DATE
    * Статус: VARCHAR
}

Пользователь ||--o{ Заказ : "размещает"
Пользователь ||--o{ Отзыв : "оставляет"
Пользователь ||--o{ Уведомление : "получает"
Товар ||--o{ Отзыв : "получает"
Заказ }o--|| Товар : "содержит"
@enduml

